name:                early
version:             0.0.0
github:              "inflex-io/early"
license:             BSD3
author:              Sky Above Limited
maintainer:          chris@skyabove.io
copyright:           "2021 Chris Done"
description:         Please see the README on GitHub at <https://github.com/inflex-io/early#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  ghc-options:
    - -Wall
  dependencies:
  - ghc
  - syb
  - text
  - transformers
  - containers

executables:
  early:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - ghc-lib-parser
    - text
    - unordered-containers

tests:
  early-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
      - early
